### ISSUE TITLE
Support of tag types "select" would be great

### ISSUE THREAD

**Issue by feonit** [macek/jquery-serialize-object#26]
form
  select
    option>add me to the serializeObject</option
 /select
/form

**Comment by DrewBe121212** [comment]
Hi Macek,

When will 3.x be publicly available? I am also running across this issue, and adding the ending brackets onto the end of the select name is not an option. (We are using Adobe Cold Fusion). ColdFusion works by sending the same field name multiple times (vs bracket notation to create an array).

**Comment by macek** [comment]
@DrewBe121212 I've been busy working on some other things in the meantime. I'll try to return to `3.x` as soon as I can. My apologies for the delay.
