### ISSUE TITLE
Support "dot" notation for object property names

### ISSUE THREAD

**Issue by macgyver** [macek/jquery-serialize-object#4]
This is a rad plugin!  I personally think it would be cool if it also supported dot notation, e.g:

``` html
<input name="dream.as.vividly.as.you.can" value="g">
```

would parse the same as:

``` html
<input name="dream[as][vividly][as][you][can]" value="g">
```

**Comment by thanhngch** [comment]
> @macgyver i just wanted to follow up and let you know some things have changed that can support the dot notation now.
> 
> Please see [this comment](https://github.com/macek/jquery-serialize-object/issues/6#issuecomment-37358931) from another issue.
> 
> Also, please see the update [API](https://github.com/macek/jquery-serialize-object#api) documentation. I've included this example to support dot notation.
> 
> ```js
> $.extend(FormSerializer.patterns, {
>   validate: /^[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)*(?:\[\])?$/i
> });
> ```
> 
> Here's a [fiddle demo](http://jsfiddle.net/macek/3CJZ2/)

If you're using compose dot and bracket (like `friend[0].nick`) Using 
```js
$.extend(FormSerializer.patterns, {
    validate: /^[a-z][a-z0-9_]*(?:(?:\.[a-z0-9_]+)|(?:\[[a-z0-9_]+\]))*(?:\[\])?$/i
});
```
I use it and using the library jsonform (https://jsonform.github.io/jsonform) work together.

**Comment by macgyver** [comment]
Haha, ok thanks for the update ;)
