### ISSUE TITLE
Support for keys with hyphens

### ISSUE THREAD

**Issue by marcosrogers** [macek/jquery-serialize-object#48]
Thanks so much for creating this code. I was especially interested in getting hyphenated input names to work.

In using the code you provided in your Readme, I found that an input name such as `foo[bar-baz]` still does not work, but this can be fixed by updating the relevant group in the `patterns.validate` regex to include a dash, as follows:
```javascript
$.extend(FormSerializer.patterns, {
  validate: /^[a-z][a-z0-9_-]*(?:\[(?:\d*|[a-z0-9_-]+)\])*$/i,
  key:      /[a-z0-9_-]+|(?=\[\])/gi,
  named:    /^[a-z0-9_-]+$/i
});
```

**Comment by macek** [comment]
@marcosrogers thanks for submitting this issue.

I updated the regexp in the README to

```js
$.extend(FormSerializer.patterns, {
  validate: /^[a-z][a-z0-9_-]*(?:\[(?:\d*|[a-z0-9_-]+)\])*$/i,
  key:      /[a-z0-9_-]+|(?=\[\])/gi,
  named:    /^[a-z0-9_-]+$/i
});
```

The only difference here is the extra `-` in the bracketed section near the end.

I added a test in version [2.4.5](https://github.com/macek/jquery-serialize-object/releases/tag/2.4.5) to test that this regexp functions properly now
