### ISSUE TITLE
Support for Browserify

### ISSUE THREAD

**Issue by izolate** [macek/jquery-serialize-object#50]
This doesn't seem to work with [Browserify](http://browserify.org/). I see CommonJS support in the source, so apologies if the problem lies in my own code.

As I understand, setup should be pretty simple:

```
var $ = require('jquery');
require('form-serializer');
```

However I get a `TypeError: undefined is not a function` when I call `$('form').serializeObject()`, indicating the methods aren't attached to the object.

**Comment by mhamann** [comment]
I'm having the same issue.

**Comment by izolate** [comment]
Sorry to hear that. Try [form-serialize](https://www.npmjs.com/package/form-serialize), I found it to be a great replacement.

**Comment by izolate** [comment]
Didn't mean to close this.

**Comment by macek** [comment]
The `FormSerializer` constructor uses dependency injection to pass the jQuery reference

You can see examples of this all of the [unit tests](https://github.com/macek/jquery-serialize-object/tree/master/test/unit)

```js
// imports
var $ = require('jquery');
var FormSerializer = require('form-serializer');

// create new FormSerializer instance
var serializer = new FormSerializer($);

// ... 
```
