### ISSUE TITLE
jQuery 2.x

### ISSUE THREAD

**Issue by MichaelMackus** [macek/jquery-serialize-object#56]
Not sure if there's a reason for this, but the bower.json requires jQuery 1.x 

Some of the other bower libraries in my app require jQuery 2.x, so this leads to some confusing conflicts come bower install time. If I choose to use jQuery 2.x the jquery-serialize-object library works just fine (tested with jQuery 2.1.3 and a simple $('form').serializeObject()).

Any reason for the ^ [here](https://github.com/macek/jquery-serialize-object/blob/master/bower.json#L9)? Can we just change that to a >=?

Cheers

**Comment by macek** [comment]
@MichaelMackus thanks for submitting this issue. I've loosened the requirement to `>= 1.2` which should help everyone that's been struggling with this.

Go ahead an grab [2.4.4](https://github.com/macek/jquery-serialize-object/releases/tag/2.4.4) that includes the patch
