### ISSUE TITLE
Test all keys before deciding on 'fixed' array

### ISSUE THREAD

**Issue by mnpenner** [macek/jquery-serialize-object#58]
I had a form with a mix of numeric and string keys. This serializer decided my form should be serialized using a fixed array, causing me to lose chunks of the form that used named keys.

**Comment by macek** [comment]
Yeah, that's the current behavior of the plugin and this is not considered (by me) to be a bug.

I'm currently working toward the [W3C HTML JSON form submission spec](http://www.w3.org/TR/2014/WD-html-json-forms-20140529/) which won't have this "bug".

I've been pretty busy with some other stuff lately, but keep your eyes open for `3.x` in the future.
