### ISSUE TITLE
Support for disabled fields

### ISSUE THREAD

**Issue by victorwpbastos** [macek/jquery-serialize-object#60]
Would be great if we can tell to jquery-serialize-object to return disabled fields too. Something like:

```js
$('form').serializeObject({getDisabled: true});
```

**Comment by Florian-R** [comment]
This plugin use [jQuery.serializeArray](http://api.jquery.com/serializeArray/) under the hood, which only includes "successful controls", so it's not feasible at the moment.

One dirty workaround could be to remove the disabled attributes of such controls, serialize the form and then put it back.

**Comment by macek** [comment]
The form

```html
<input name="a" value="1">
<input name="b" value="2" disabled>
```

is serialized as

```js
var obj = form.serializeObject();
// => {a: "1"}
```

-----

The values here

```js
form.a; //=> "1"
form.b; //=> undefined
```
match specification and are what I would expect

**Comment by malles** [comment]
I agree on that. If you must have the values of those inputs, they shouldn't be disabled in the first place, or you should grab the values via custom scripts

**Comment by billdanbury** [comment]
I believe there is a distinction to be made between "locked" and "unwanted" values. Unfortunately, the spec doesn't give us this nuance... So a flag should be introduced that will provide the data (without more hackery)

**Comment by ValeryIvanov** [comment]
Even tho I dont care about this feature, I do agree with @billdanbury

**Comment by macek** [comment]
@billdanbury @ValeryIvanov if the value is locked, it is already set somewhere else and therefore does not need to be submitted along with the form data.

**Comment by ValeryIvanov** [comment]
@macek Yes I do agree with you, that is what should be done in all applications, unfortunately many of us have to work with legacy application that may not follow this logic and thus need to overcome these kind of limitations (via switches/configuration). Refactoring legacy applications to support whatever libraries expect cannot be always an option (for example too much work). I dont mean to be rude, just tring to explain users perception of how things could be built (in this case more configurable library)
