### ISSUE TITLE
serialize to result start with array []

### ISSUE THREAD

**Issue by sckoh** [macek/jquery-serialize-object#61]
```html
<input name="foo[]" value="10">
<input name="foo[]" value="20">
```

serialize into

```js
{foo: [10, 20]}
```

How can I serialize a form into below without the key 'foo'

```js
[10, 20]
```

**Comment by macek** [comment]
Serializing to an unnamed array is not possible using this plugin. When submitting form data, values should be associated to keys in some way.

As I work toward the [W3C HTML JSON form submission spec](http://www.w3.org/TR/html-json-forms/) it's not likely to be added in the future either.
