### ISSUE TITLE
Standalone JSON String Parse

### ISSUE THREAD

**Issue by dovy** [macek/jquery-serialize-object#64]
I love the concept, but I'm working with a framework that provides me a json string already. I'd love to just pass this in and parse it. Is this possible?

**Comment by macek** [comment]
@dovy well you certainly don't need my plugin to parse JSON :)

```js
var obj = JSON.parse(json);
```

Now you have a perfectly usable JS object.

**Comment by dovy** [comment]
I was talking about something previously serialized into an object. But no worries, I got it sorted.  ;)
