### ISSUE TITLE
Support inputs without form

### ISSUE THREAD

**Issue by andrews05** [macek/jquery-serialize-object#65]
The jQuery serialize functions can be called on either a form element a collection of individual inputs. When I try using serializeObject on a collection of inputs, it says "jquery-serialize-object can only serialize one form at a time".

**Comment by photoart-mtlwebdev** [comment]
Hi,

Same problem here.
I'd like to serialize only a part of the form, within a div.

**Comment by macek** [comment]
I just published version `2.5.0` which allows you to serialize multiple elements

Please read the specified behavior in [selector-test.js](https://github.com/macek/jquery-serialize-object/blob/master/test/integration/selector-test.js) for more info.

**Comment by photoart-mtlwebdev** [comment]
Great :-)

Thanks a lot.

**Comment by MitchelEvn** [comment]
I am currently having issues with this in IE (v. 11 to be specific). Seems to be serialize containing elements in firefox and chrome just fine. Any ideas why this may be happening?
