### ISSUE TITLE
Support composer

### ISSUE THREAD

**Issue by damnedest** [macek/jquery-serialize-object#66]
Can you add support for composer? Version in NPM is outdated (

**Comment by macek** [comment]
npm is updated with version 2.5.0 now

**Comment by macek** [comment]
NPM is updated with version [2.5.0](https://www.npmjs.com/package/form-serializer) now

This is not a PHP package. It will not be supported on composer.

**Comment by damnedest** [comment]
jQuery is also no PHP package, but it supports composer. Composer automatically updates current version of package inside and only two things you need to do:
 * add composer.json
 * add hook on repository

After this you can forget about composer.

**Comment by damnedest** [comment]
Supports from component installer. Is different thing ) Ok, bootstrap supports composer.
