### ISSUE TITLE
Forms with dash ("-") in name doesn't serialize correctly

### ISSUE THREAD

**Issue by troygrosfield** [macek/jquery-serialize-object#76]
Forms don't serialize correctly when the form field has a dash ("-") in the ``name`` attribute:

**Html**

```html
<form id="myForm">
  <input type="text" name="test" value="works">
  <input type="text" name="test-2" value="should work">
</form>
```

**Actual output**
```js
> $('#myForm').serializeObject()
{
  'test': 'works'
}
```

**Expected output**
```js
> $('#myForm').serializeObject()
{
  'test': 'works',
  'test-2': 'should work'
}
```

**Comment by macek** [comment]
At the very least, please read the `README` before posting an issue.

**Comment by troygrosfield** [comment]
I did read the ``README`` apparently I missed the part I was looking for.  However, why wouldn't this be the default behavior?  In what circumstance would you not want to use a hyphen in the field name?

**Comment by troygrosfield** [comment]
Changes would be something along the lines of:

```
  var patterns = {
    validate: /^[a-z_][a-z0-9_]*(?:\[(?:\d*|[a-z0-9_]+)\])*$/i,
    key:      /[a-z0-9_]+|(?=\[\])/gi,
    push:     /^$/,
    fixed:    /^\d+$/,
    named:    /^[a-z0-9_]+$/i,
    allowAllPatterns: false
  };

...

function addPair(pair) {
  if (!patterns.allowAllPatterns && !patterns.validate.test(pair.name)) return this;
  var obj = makeObject(pair.name, encode(pair));
  data = helper.extend(true, data, obj);
  return this;
}
```

Passive change that makes the additional config of "use all form field names as-is" easier.  

Thoughts?
