### ISSUE TITLE
dot notation ignored

### ISSUE THREAD

**Issue by alfredopacino** [macek/jquery-serialize-object#79]
Hi,
thanks a lot for your plugin, I mean it.
I just tried to name an input field "reg.number".
I was expecting the same result as "reg[number]"
But the plugin totally ignore that field!

**Comment by macek** [comment]
Please see #4. Dot notation functionality is also backed by a [unit test](https://github.com/macek/jquery-serialize-object/blob/68ec73289dcffa533770f07616633696c552bf6a/test/unit/pattern-test.js#L20-L30). And it's covered in the [README](https://github.com/macek/jquery-serialize-object#api) ...

Quick recap

```js
$.extend(FormSerializer.patterns, {
  validate: /^[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)*(?:\[\])?$/i
});

var data = $('#form').serializeObject();
```
