### ISSUE TITLE
Dash (minus) is valid in JSON key, but form fields that contain dashes do not seem to be parsed

### ISSUE THREAD

**Issue by Clearnine** [macek/jquery-serialize-object#84]
I had a form with a number of field names with dashes.  The form name also contained a dash.  I did not exhaustivly test to determine if one or the other or both are the problem.

After hacking at it for about an hour I changed the dashes to underscores and everything worked.

**Comment by macek** [comment]
Unfriendly as it may be, the [API docs](https://github.com/macek/jquery-serialize-object#api) clearly demonstrate how to override the internal regexp patterns used to power this plugin. I agree that the defaults are a bit opinionated, but some solutions to ease some of those pains are in the works. See #81 for more details.
