### ISSUE TITLE
Very slow with big forms

### ISSUE THREAD

**Issue by danielsantiago** [macek/jquery-serialize-object#86]
Hi,

I'm having a performance problem with a form that have more than 800 fields (don't ask me why). It's taking more than 250ms to execute "serializeJSON".

I notice that is when calling "tryToFindTypeFromDataAttr". Is there a way to skip the type check from the dom?

**Comment by danielsantiago** [comment]
My temporary fix:

```
function getFormValues() {

    //Prevent serializeJSON from checking types
    var tempFn = $.serializeJSON.tryToFindTypeFromDataAttr;

    $.serializeJSON.tryToFindTypeFromDataAttr = function() { return null; };

    var values = $('#Form').serializeJSON();

    $.serializeJSON.tryToFindTypeFromDataAttr = tempFn;

    return values;
}
```

**Comment by macek** [comment]
I think you might have the wrong plugin repository. I'm aware there are other `serializeJSON` or `serializeObject` plugins, but that API is not ours. Also, you [won't find `tryToFindTypeFromDataAttr` anywhere in our source code](https://github.com/macek/jquery-serialize-object/search?utf8=%E2%9C%93&q=tryToFindTypeFromDataAttr).

Let me know if I can help you out in any other way.
