### ISSUE TITLE
when select with multiple property, can't be work

### ISSUE THREAD

**Issue by chloe899** [macek/jquery-serialize-object#96]
&lt;select multiple="multiple" name="test"&gt;
    &lt;option selected&gt;a&lt;/option&gt;
    &lt;option selected&gt;b&lt;/option&gt;
    &lt;option selected&gt;c&lt;/option&gt;
&lt;/select&gt;

**Comment by macek** [comment]
make sure you change the `name` attribute as follows

```html
<select name="test[]" multiple> ...
```
